version: '3.4'

services:
  postgres:
    container_name: sample_db
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgres/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: sample
      POSTGRES_PASSWORD: sample

volumes:
  postgres_data:
